modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "optionsprofiles"
version = "${version}"
displayName = "Options Profiles"
authors = "AxolotlMaid"
description = '''
Load and save your options from in-game.
'''
logoFile = "icon.png"

[[dependencies.optionsprofiles]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.optionsprofiles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.optionsprofiles]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.68,)"
ordering = "AFTER"
side = "BOTH"
